/**
 * Official AWS Workshop data - Batch 3 (50 more workshops)
 * All from official AWS sources
 */
import { res, WorkshopDef } from "./workshop-data";

export const workshops3: WorkshopDef[] = [
  // ── Security Advanced ──
  { workshopId: "detective-workshop", title: "Amazon Detective Workshop", description: "Investigate security findings with Amazon Detective using graph analysis of CloudTrail, VPC Flow Logs, and GuardDuty.", category: "Security", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/detective/", instructions: "Enable Detective, investigate findings, analyze entity behaviors, trace security events across accounts", resources: [res("detective-dw-1","AWS::Detective::Graph",0.002)] },
  { workshopId: "macie-workshop", title: "Amazon Macie Workshop", description: "Discover and protect sensitive data in S3 with Amazon Macie using machine learning for data classification.", category: "Security", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/macie/", instructions: "Enable Macie, create classification jobs, review sensitive data findings, configure automated remediation", resources: [res("macie-mw-1","AWS::Macie::Session",0.001), res("s3-mw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "secrets-manager-workshop", title: "AWS Secrets Manager Workshop", description: "Manage application secrets securely with AWS Secrets Manager including automatic rotation and cross-account access.", category: "Security", difficulty: "intermediate", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/secrets-manager/", instructions: "Store secrets, configure automatic rotation with Lambda, implement cross-account access, integrate with RDS", resources: [res("sm-sm-1","AWS::SecretsManager::Secret",0.0006), res("lambda-sm-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "kms-workshop", title: "AWS KMS Workshop", description: "Implement encryption at scale with AWS Key Management Service for data protection and key management.", category: "Security", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/kms/", instructions: "Create KMS keys, encrypt S3 objects, implement envelope encryption, configure key policies and grants", resources: [res("kms-kw-1","AWS::KMS::Key",0.001), res("s3-kw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "inspector-workshop", title: "Amazon Inspector Workshop", description: "Automate vulnerability management with Amazon Inspector for EC2 instances, Lambda functions, and container images.", category: "Security", difficulty: "intermediate", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/inspector/", instructions: "Enable Inspector, scan EC2 instances and Lambda functions, review vulnerability findings, configure suppression rules", resources: [res("ec2-iw-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("lambda-iw-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "sso-workshop", title: "AWS IAM Identity Center Workshop", description: "Implement single sign-on with AWS IAM Identity Center (formerly SSO) for centralized access management.", category: "Security", difficulty: "advanced", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/iam/identity-center/", instructions: "Configure Identity Center, create permission sets, assign users to accounts, integrate with external IdP", resources: [res("sso-sw-1","AWS::SSO::PermissionSet",0,{freeTier:true})] },
  // ── Networking Advanced ──
  { workshopId: "route53-workshop", title: "Amazon Route 53 Workshop", description: "Implement DNS management and traffic routing with Route 53 including health checks and failover.", category: "Networking", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/route53/", instructions: "Create hosted zones, configure routing policies, set up health checks, implement DNS failover", resources: [res("r53-rw-1","AWS::Route53::HostedZone",0.0007)] },
  { workshopId: "global-accelerator-workshop", title: "AWS Global Accelerator Workshop", description: "Improve application availability and performance with AWS Global Accelerator for global traffic management.", category: "Networking", difficulty: "advanced", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/global-accelerator/", instructions: "Create accelerator, configure listeners and endpoint groups, implement traffic dials, test failover", resources: [res("ga-gw-1","AWS::GlobalAccelerator::Accelerator",0.025), res("alb-gw-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225)] },
  { workshopId: "elb-workshop", title: "Elastic Load Balancing Workshop", description: "Distribute traffic with Application, Network, and Gateway Load Balancers for high availability.", category: "Networking", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/elasticloadbalancing/", instructions: "Create ALB and NLB, configure target groups, implement path-based routing, set up SSL/TLS termination", resources: [res("alb-ew-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225), res("ec2-ew-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "direct-connect-workshop", title: "AWS Direct Connect Workshop", description: "Establish dedicated network connections from on-premises to AWS with Direct Connect.", category: "Networking", difficulty: "advanced", estimatedDuration: 180, costBadge: "high", sourceUrl: "https://aws.amazon.com/directconnect/", instructions: "Configure virtual interfaces, set up BGP peering, implement redundant connections, test failover scenarios", resources: [res("dx-dw-1","AWS::DirectConnect::Connection",0.03)] },
  // ── Analytics Advanced ──
  { workshopId: "opensearch-workshop", title: "Amazon OpenSearch Service Workshop", description: "Build search and analytics solutions with Amazon OpenSearch Service for log analytics and full-text search.", category: "Analytics", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/opensearch-service/", instructions: "Create OpenSearch domain, ingest data with Logstash, build Kibana dashboards, implement search queries", resources: [res("opensearch-ow-1","AWS::OpenSearchService::Domain",0.036,{instanceType:"t3.small.search"})] },
  { workshopId: "mwaa-workshop", title: "Amazon MWAA Workshop", description: "Orchestrate data pipelines with Amazon Managed Workflows for Apache Airflow.", category: "Analytics", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/managed-workflows-for-apache-airflow/", instructions: "Create MWAA environment, write DAGs, configure connections, monitor workflow execution", resources: [res("mwaa-mw-1","AWS::MWAA::Environment",0.049)] },
  { workshopId: "clean-rooms-workshop", title: "AWS Clean Rooms Workshop", description: "Collaborate on data analysis without sharing raw data using AWS Clean Rooms for privacy-preserving analytics.", category: "Analytics", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/clean-rooms/", instructions: "Create collaborations, configure analysis rules, run privacy-safe queries, review results", resources: [res("cleanrooms-cr-1","AWS::CleanRooms::Collaboration",0)] },
  { workshopId: "lake-formation-workshop", title: "AWS Lake Formation Workshop", description: "Build and manage secure data lakes with AWS Lake Formation for centralized governance and access control.", category: "Analytics", difficulty: "advanced", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/lake-formation/", instructions: "Register data lake locations, configure permissions, create databases and tables, implement fine-grained access", resources: [res("lf-lw-1","AWS::LakeFormation::DataLakeSettings",0), res("s3-lw-1","AWS::S3::Bucket",0,{freeTier:true}), res("glue-lw-1","AWS::Glue::Crawler",0.0044)] },
  // ── Generative AI ──
  { workshopId: "bedrock-agents-workshop", title: "Amazon Bedrock Agents Workshop", description: "Build autonomous AI agents with Amazon Bedrock Agents for task automation and knowledge retrieval.", category: "Machine Learning", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/bedrock/agents/", instructions: "Create Bedrock agent, define action groups, configure knowledge bases, implement guardrails", resources: [res("bedrock-ba-1","AWS::Bedrock::Agent",0.01), res("s3-ba-1","AWS::S3::Bucket",0,{freeTier:true}), res("lambda-ba-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "bedrock-rag-workshop", title: "Bedrock RAG Workshop", description: "Build Retrieval Augmented Generation applications with Amazon Bedrock Knowledge Bases and vector stores.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/bedrock/knowledge-bases/", instructions: "Create knowledge base, configure vector store with OpenSearch, ingest documents, query with RAG", resources: [res("bedrock-rag-1","AWS::Bedrock::KnowledgeBase",0.01), res("opensearch-rag-1","AWS::OpenSearchServerless::Collection",0.024), res("s3-rag-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "sagemaker-studio-workshop", title: "Amazon SageMaker Studio Workshop", description: "Use SageMaker Studio IDE for end-to-end ML development with notebooks, experiments, and model registry.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/sagemaker/studio/", instructions: "Set up SageMaker Studio domain, create notebooks, run experiments, register models, deploy endpoints", resources: [res("sagemaker-ss-1","AWS::SageMaker::Domain",0.0464,{instanceType:"ml.t3.medium"})] },
  { workshopId: "sagemaker-pipelines", title: "SageMaker Pipelines Workshop", description: "Build MLOps pipelines with SageMaker Pipelines for automated model training, evaluation, and deployment.", category: "Machine Learning", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/sagemaker/pipelines/", instructions: "Define pipeline steps, configure processing and training jobs, implement model approval, automate deployment", resources: [res("sagemaker-sp-1","AWS::SageMaker::Pipeline",0.0464,{instanceType:"ml.t3.medium"}), res("s3-sp-1","AWS::S3::Bucket",0.001)] },
  // ── Resilience & Disaster Recovery ──
  { workshopId: "resilience-hub-workshop", title: "AWS Resilience Hub Workshop", description: "Assess and improve application resilience with AWS Resilience Hub for RTO/RPO validation.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/resilience-hub/", instructions: "Define application, set resilience policies, run assessments, review recommendations, implement improvements", resources: [res("ec2-rh-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "disaster-recovery-workshop", title: "AWS Disaster Recovery Workshop", description: "Implement disaster recovery strategies on AWS including pilot light, warm standby, and multi-site active-active.", category: "DevOps", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/disaster-recovery/", instructions: "Set up pilot light DR, configure warm standby, implement Route 53 failover, test recovery procedures", resources: [res("ec2-dr-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("rds-dr-1","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true}), res("r53-dr-1","AWS::Route53::HealthCheck",0.0007)] },
  { workshopId: "multi-region-workshop", title: "Multi-Region Architecture Workshop", description: "Design and implement multi-region architectures on AWS for global applications with high availability.", category: "DevOps", difficulty: "advanced", estimatedDuration: 480, costBadge: "high", sourceUrl: "https://aws.amazon.com/solutions/implementations/multi-region-application-architecture/", instructions: "Deploy across regions, configure DynamoDB global tables, set up Aurora global database, implement Route 53 routing", resources: [res("dynamodb-mr-1","AWS::DynamoDB::GlobalTable",0.025), res("aurora-mr-1","AWS::RDS::GlobalCluster",0.12,{instanceType:"db.r5.large"}), res("r53-mr-1","AWS::Route53::HostedZone",0.0007)] },
  // ── End User Computing ──
  { workshopId: "workspaces-workshop", title: "Amazon WorkSpaces Workshop", description: "Deploy virtual desktops with Amazon WorkSpaces for secure remote access to cloud-based desktops.", category: "End User Computing", difficulty: "intermediate", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/workspaces/", instructions: "Create WorkSpaces directory, provision desktops, configure access policies, manage images and bundles", resources: [res("workspaces-ww-1","AWS::WorkSpaces::Workspace",0.028)] },
  { workshopId: "appstream-workshop", title: "Amazon AppStream 2.0 Workshop", description: "Stream desktop applications to users with Amazon AppStream 2.0 for application delivery.", category: "End User Computing", difficulty: "intermediate", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/appstream2/", instructions: "Create AppStream fleet, configure image builder, publish applications, manage user access", resources: [res("appstream-aw-1","AWS::AppStream::Fleet",0.05,{instanceType:"stream.standard.medium"})] },
  // ── Media Services ──
  { workshopId: "mediaconvert-workshop", title: "AWS Elemental MediaConvert Workshop", description: "Transcode video content at scale with AWS Elemental MediaConvert for broadcast and streaming.", category: "Media Services", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/mediaconvert/", instructions: "Create transcoding jobs, configure output groups, implement HLS packaging, set up job templates", resources: [res("s3-mc-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "ivs-workshop", title: "Amazon IVS Workshop", description: "Build interactive live streaming experiences with Amazon Interactive Video Service.", category: "Media Services", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/ivs/", instructions: "Create IVS channel, configure streaming, implement chat, build interactive player", resources: [res("ivs-iw-1","AWS::IVS::Channel",0.02)] },
  // ── Blockchain ──
  { workshopId: "managed-blockchain-workshop", title: "Amazon Managed Blockchain Workshop", description: "Build blockchain networks with Amazon Managed Blockchain using Hyperledger Fabric.", category: "Blockchain", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/managed-blockchain/", instructions: "Create blockchain network, add members, deploy chaincode, invoke transactions, query ledger", resources: [res("amb-mb-1","AWS::ManagedBlockchain::Member",0.052)] },
  // ── Game Development ──
  { workshopId: "gamelift-workshop", title: "Amazon GameLift Workshop", description: "Deploy and scale multiplayer game servers with Amazon GameLift for session-based gaming.", category: "Game Development", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/gamelift/", instructions: "Upload game server build, create fleet, configure matchmaking, implement game sessions", resources: [res("gamelift-gw-1","AWS::GameLift::Fleet",0.057,{instanceType:"c5.large"})] },
  // ── Sustainability ──
  { workshopId: "sustainability-workshop", title: "AWS Sustainability Workshop", description: "Measure and reduce the environmental impact of cloud workloads with AWS sustainability tools.", category: "Management & Governance", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/sustainability/", instructions: "Use Customer Carbon Footprint Tool, optimize resource utilization, implement right-sizing, reduce data transfer", resources: [res("ec2-sw-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  // ── Hybrid & Edge ──
  { workshopId: "outposts-workshop", title: "AWS Outposts Workshop", description: "Extend AWS infrastructure to on-premises with AWS Outposts for low-latency hybrid workloads.", category: "Compute", difficulty: "advanced", estimatedDuration: 180, costBadge: "high", sourceUrl: "https://aws.amazon.com/outposts/", instructions: "Configure Outposts rack, deploy EC2 instances locally, run ECS on Outposts, implement hybrid architectures", resources: [res("ec2-op-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  { workshopId: "wavelength-workshop", title: "AWS Wavelength Workshop", description: "Deploy ultra-low latency applications at 5G network edges with AWS Wavelength zones.", category: "Compute", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/wavelength/", instructions: "Create Wavelength zone resources, deploy EC2 instances at edge, configure carrier gateway, test latency", resources: [res("ec2-wl-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  { workshopId: "snow-family-workshop", title: "AWS Snow Family Workshop", description: "Process data at the edge and migrate large datasets with AWS Snow Family devices.", category: "Migration", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/snow/", instructions: "Order Snow device, configure compute instances, transfer data, manage with OpsHub", resources: [res("s3-sf-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Contact Center ──
  { workshopId: "connect-workshop", title: "Amazon Connect Workshop", description: "Build cloud contact centers with Amazon Connect for omnichannel customer engagement.", category: "Application Integration", difficulty: "intermediate", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/connect/", instructions: "Create Connect instance, design contact flows, configure queues and routing, add chat and task channels", resources: [res("connect-cw-1","AWS::Connect::Instance",0.018)] },
  // ── Supply Chain ──
  { workshopId: "supply-chain-workshop", title: "AWS Supply Chain Workshop", description: "Optimize supply chain operations with AWS Supply Chain for demand planning and inventory management.", category: "Application Integration", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/aws-supply-chain/", instructions: "Set up data lake, configure demand forecasting, implement inventory optimization, build supply chain dashboards", resources: [res("s3-scw-1","AWS::S3::Bucket",0,{freeTier:true}), res("forecast-scw-1","AWS::Forecast::Dataset",0.05)] },
  // ── Additional Serverless ──
  { workshopId: "eventbridge-pipes", title: "Amazon EventBridge Pipes Workshop", description: "Connect event producers to consumers with EventBridge Pipes for point-to-point integrations.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 90, costBadge: "free", sourceUrl: "https://aws.amazon.com/eventbridge/pipes/", instructions: "Create pipes from SQS to Step Functions, configure filtering and enrichment, implement error handling", resources: [res("sqs-ep-1","AWS::SQS::Queue",0,{freeTier:true}), res("stepfn-ep-1","AWS::StepFunctions::StateMachine",0,{freeTier:true})] },
  { workshopId: "scheduler-workshop", title: "Amazon EventBridge Scheduler Workshop", description: "Schedule tasks at scale with Amazon EventBridge Scheduler for one-time and recurring invocations.", category: "Serverless", difficulty: "beginner", estimatedDuration: 60, costBadge: "free", sourceUrl: "https://aws.amazon.com/eventbridge/scheduler/", instructions: "Create one-time and recurring schedules, target Lambda and Step Functions, implement flexible time windows", resources: [res("lambda-es-1","AWS::Lambda::Function",0,{freeTier:true})] },
  // ── Additional DevOps ──
  { workshopId: "terraform-workshop", title: "Terraform on AWS Workshop", description: "Provision AWS infrastructure with HashiCorp Terraform using HCL for infrastructure as code.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/terraform/", instructions: "Write Terraform configurations, manage state with S3 backend, use modules, implement CI/CD for IaC", resources: [res("s3-tw-1","AWS::S3::Bucket",0,{freeTier:true}), res("ec2-tw-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "eks-terraform-workshop", title: "EKS with Terraform Workshop", description: "Deploy and manage Amazon EKS clusters using Terraform with EKS Blueprints add-ons.", category: "Containers", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Create EKS cluster with Terraform, configure add-ons, deploy workloads, implement GitOps with ArgoCD", resources: [res("eks-et-1","AWS::EKS::Cluster",0.10), res("ec2-et-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("ec2-et-2","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  { workshopId: "gitops-workshop", title: "GitOps on EKS Workshop", description: "Implement GitOps workflows on Amazon EKS with Flux and ArgoCD for declarative cluster management.", category: "Containers", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Set up Flux or ArgoCD, configure Git repositories, deploy applications declaratively, implement progressive delivery", resources: [res("eks-go-1","AWS::EKS::Cluster",0.10), res("ec2-go-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  // ── Additional Compute ──
  { workshopId: "hpc-workshop", title: "AWS HPC Workshop", description: "Run high-performance computing workloads on AWS with ParallelCluster, FSx for Lustre, and Batch.", category: "Compute", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/hpc/", instructions: "Deploy ParallelCluster, configure Slurm scheduler, mount FSx for Lustre, submit HPC jobs", resources: [res("ec2-hpc-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("fsx-hpc-1","AWS::FSx::FileSystem",0.14,{storageSize:1200})] },
  { workshopId: "lambda-perf-workshop", title: "Lambda Performance Optimization Workshop", description: "Optimize AWS Lambda function performance with cold start reduction, memory tuning, and SnapStart.", category: "Serverless", difficulty: "advanced", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/lambda/", instructions: "Profile Lambda functions, optimize memory settings, implement SnapStart for Java, reduce cold starts with provisioned concurrency", resources: [res("lambda-lpo-1","AWS::Lambda::Function",0,{freeTier:true})] },
  // ── Additional Storage ──
  { workshopId: "s3-security-workshop", title: "Amazon S3 Security Workshop", description: "Secure S3 buckets with bucket policies, access points, Object Lock, and S3 Access Grants.", category: "Storage", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/s3/security/", instructions: "Configure bucket policies, implement access points, enable Object Lock, set up S3 Access Grants", resources: [res("s3-ss-1","AWS::S3::Bucket",0,{freeTier:true}), res("s3-ss-2","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "transfer-family-workshop", title: "AWS Transfer Family Workshop", description: "Set up managed SFTP, FTPS, and FTP servers with AWS Transfer Family for secure file transfers.", category: "Storage", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/aws-transfer-family/", instructions: "Create Transfer Family server, configure SFTP endpoint, set up S3 backend, manage user access", resources: [res("transfer-tf-1","AWS::Transfer::Server",0.03), res("s3-tf-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Additional Migration ──
  { workshopId: "map-workshop", title: "AWS Migration Acceleration Program Workshop", description: "Plan and execute large-scale migrations with the AWS Migration Acceleration Program methodology.", category: "Migration", difficulty: "advanced", estimatedDuration: 480, costBadge: "medium", sourceUrl: "https://aws.amazon.com/migration-acceleration-program/", instructions: "Assess migration readiness, build business case, plan migration waves, execute and optimize", resources: [res("ec2-map-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("dms-map-1","AWS::DMS::ReplicationInstance",0.018,{instanceType:"dms.t3.micro"})] },
  { workshopId: "modernization-workshop", title: "Application Modernization Workshop", description: "Modernize legacy applications on AWS using containers, serverless, and microservices patterns.", category: "Migration", difficulty: "advanced", estimatedDuration: 480, costBadge: "medium", sourceUrl: "https://aws.amazon.com/modernization/", instructions: "Assess application portfolio, decompose monolith, containerize services, implement serverless components", resources: [res("ecs-mw-1","AWS::ECS::Cluster",0), res("fargate-mw-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("lambda-mw-1","AWS::Lambda::Function",0,{freeTier:true})] },
];
