/**
 * Official AWS Workshop data - Batch 2 (50 more workshops)
 * All from official AWS sources
 */
import { res, WorkshopDef } from "./workshop-data";

export const workshops2: WorkshopDef[] = [
  // ── Application Integration ──
  { workshopId: "appsync-workshop", title: "AWS AppSync Workshop", description: "Build real-time GraphQL APIs with AWS AppSync, DynamoDB resolvers, and subscription-based updates.", category: "Application Integration", difficulty: "intermediate", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/appsync/", instructions: "Create AppSync API, define GraphQL schema, configure DynamoDB resolvers, implement real-time subscriptions", resources: [res("appsync-as-1","AWS::AppSync::GraphQLApi",0,{freeTier:true}), res("dynamodb-as-1","AWS::DynamoDB::Table",0,{freeTier:true})] },
  { workshopId: "api-gateway-workshop", title: "Amazon API Gateway Workshop", description: "Build REST and WebSocket APIs with Amazon API Gateway including authorization, throttling, and caching.", category: "Application Integration", difficulty: "intermediate", estimatedDuration: 150, costBadge: "free", sourceUrl: "https://aws.amazon.com/api-gateway/", instructions: "Create REST API, configure Lambda integration, set up Cognito authorizer, implement usage plans and API keys", resources: [res("apigw-ag-1","AWS::ApiGateway::RestApi",0,{freeTier:true}), res("lambda-ag-1","AWS::Lambda::Function",0,{freeTier:true}), res("cognito-ag-1","AWS::Cognito::UserPool",0,{freeTier:true})] },
  { workshopId: "sns-sqs-fanout", title: "SNS/SQS Fanout Pattern Workshop", description: "Implement pub/sub messaging patterns with Amazon SNS and SQS for decoupled microservices.", category: "Application Integration", difficulty: "beginner", estimatedDuration: 90, costBadge: "free", sourceUrl: "https://aws.amazon.com/sns/", instructions: "Create SNS topics, configure SQS subscriptions, implement fanout pattern, add dead-letter queues", resources: [res("sns-sf-1","AWS::SNS::Topic",0,{freeTier:true}), res("sqs-sf-1","AWS::SQS::Queue",0,{freeTier:true}), res("sqs-sf-2","AWS::SQS::Queue",0,{freeTier:true})] },
  { workshopId: "mq-workshop", title: "Amazon MQ Workshop", description: "Deploy managed message brokers with Amazon MQ for ActiveMQ and RabbitMQ workloads.", category: "Application Integration", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/amazon-mq/", instructions: "Create Amazon MQ broker, configure queues and topics, implement producer/consumer patterns, set up network of brokers", resources: [res("mq-mq-1","AWS::AmazonMQ::Broker",0.065,{instanceType:"mq.t3.micro"})] },
  { workshopId: "msk-workshop", title: "Amazon MSK Workshop", description: "Build streaming data pipelines with Amazon Managed Streaming for Apache Kafka.", category: "Application Integration", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/msk/", instructions: "Create MSK cluster, produce and consume messages, configure connectors, implement stream processing", resources: [res("msk-mk-1","AWS::MSK::Cluster",0.21,{instanceType:"kafka.m5.large"}), res("ec2-mk-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  // ── Front-End Web & Mobile ──
  { workshopId: "amplify-workshop", title: "AWS Amplify Workshop", description: "Build full-stack web and mobile apps with AWS Amplify including authentication, API, storage, and hosting.", category: "Front-End Web & Mobile", difficulty: "beginner", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/amplify/", instructions: "Initialize Amplify project, add authentication, create GraphQL API, configure storage, deploy hosting", resources: [res("amplify-aw-1","AWS::Amplify::App",0,{freeTier:true}), res("cognito-aw-1","AWS::Cognito::UserPool",0,{freeTier:true}), res("appsync-aw-1","AWS::AppSync::GraphQLApi",0,{freeTier:true})] },
  { workshopId: "pinpoint-workshop", title: "Amazon Pinpoint Workshop", description: "Engage customers with targeted messaging campaigns using Amazon Pinpoint across email, SMS, and push.", category: "Front-End Web & Mobile", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/pinpoint/", instructions: "Create Pinpoint project, import user segments, design email templates, configure campaigns, analyze engagement", resources: [res("pinpoint-pw-1","AWS::Pinpoint::App",0.001)] },
  { workshopId: "location-service-workshop", title: "Amazon Location Service Workshop", description: "Add maps, geofencing, and route planning to applications with Amazon Location Service.", category: "Front-End Web & Mobile", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/location-service/", instructions: "Create map resources, add place search, configure geofences, implement route calculation", resources: [res("location-ls-1","AWS::Location::Map",0.004), res("location-ls-2","AWS::Location::GeofenceCollection",0)] },
  // ── Management & Governance ──
  { workshopId: "config-workshop", title: "AWS Config Workshop", description: "Monitor and audit AWS resource configurations with AWS Config rules and conformance packs.", category: "Management & Governance", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/config/", instructions: "Enable AWS Config, create custom rules, deploy conformance packs, set up remediation actions", resources: [res("config-cw-1","AWS::Config::ConfigurationRecorder",0.003), res("lambda-cw-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "cloudtrail-workshop", title: "AWS CloudTrail Workshop", description: "Track API activity and user actions across your AWS infrastructure with CloudTrail and CloudTrail Lake.", category: "Management & Governance", difficulty: "intermediate", estimatedDuration: 90, costBadge: "free", sourceUrl: "https://aws.amazon.com/cloudtrail/", instructions: "Create trails, configure event selectors, query with CloudTrail Lake, set up CloudWatch alarms for API calls", resources: [res("cloudtrail-ct-1","AWS::CloudTrail::Trail",0,{freeTier:true}), res("s3-ct-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "organizations-workshop", title: "AWS Organizations Workshop", description: "Manage multiple AWS accounts with AWS Organizations, SCPs, and delegated administration.", category: "Management & Governance", difficulty: "advanced", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/organizations/", instructions: "Create organizational units, implement service control policies, configure delegated admin, manage account lifecycle", resources: [res("org-ow-1","AWS::Organizations::Organization",0,{freeTier:true})] },
  { workshopId: "cost-management-workshop", title: "AWS Cost Management Workshop", description: "Optimize cloud spending with AWS Cost Explorer, Budgets, Savings Plans, and Cost Anomaly Detection.", category: "Management & Governance", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/aws-cost-management/", instructions: "Analyze costs with Cost Explorer, create budgets and alerts, evaluate Savings Plans, configure anomaly detection", resources: [res("budget-cm-1","AWS::Budgets::Budget",0,{freeTier:true})] },
  { workshopId: "service-catalog-workshop", title: "AWS Service Catalog Workshop", description: "Create and manage catalogs of approved IT services with AWS Service Catalog for governance.", category: "Management & Governance", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/servicecatalog/", instructions: "Create portfolios, define products with CloudFormation, configure constraints, share across accounts", resources: [res("sc-sc-1","AWS::ServiceCatalog::Portfolio",0,{freeTier:true})] },
  // ── AI/ML Advanced ──
  { workshopId: "comprehend-workshop", title: "Amazon Comprehend Workshop", description: "Extract insights from text with Amazon Comprehend for sentiment analysis, entity recognition, and topic modeling.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/comprehend/", instructions: "Analyze text sentiment, detect entities, train custom classifiers, build document analysis pipelines", resources: [res("lambda-comp-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-comp-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "lex-workshop", title: "Amazon Lex Workshop", description: "Build conversational chatbots with Amazon Lex V2 for natural language understanding and dialog management.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 150, costBadge: "free", sourceUrl: "https://aws.amazon.com/lex/", instructions: "Create Lex bot, define intents and slots, configure fulfillment with Lambda, integrate with Connect", resources: [res("lex-lw-1","AWS::Lex::Bot",0,{freeTier:true}), res("lambda-lw-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "polly-workshop", title: "Amazon Polly Workshop", description: "Convert text to lifelike speech with Amazon Polly using neural and standard voices.", category: "Machine Learning", difficulty: "beginner", estimatedDuration: 60, costBadge: "free", sourceUrl: "https://aws.amazon.com/polly/", instructions: "Synthesize speech from text, use SSML for pronunciation control, create lexicons, stream audio output", resources: [res("lambda-pol-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-pol-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "translate-workshop", title: "Amazon Translate Workshop", description: "Build multilingual applications with Amazon Translate for real-time and batch text translation.", category: "Machine Learning", difficulty: "beginner", estimatedDuration: 60, costBadge: "free", sourceUrl: "https://aws.amazon.com/translate/", instructions: "Translate text in real-time, create custom terminology, batch translate documents, integrate with other services", resources: [res("lambda-tr-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "personalize-workshop", title: "Amazon Personalize Workshop", description: "Build real-time recommendation systems with Amazon Personalize for personalized user experiences.", category: "Machine Learning", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/personalize/", instructions: "Prepare interaction data, create dataset groups, train recommender models, get real-time recommendations", resources: [res("personalize-pw-1","AWS::Personalize::DatasetGroup",0.05), res("s3-pw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "forecast-workshop", title: "Amazon Forecast Workshop", description: "Generate accurate time-series forecasts with Amazon Forecast using machine learning.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/forecast/", instructions: "Import time-series data, create predictors, generate forecasts, evaluate accuracy metrics", resources: [res("s3-fc-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "kendra-workshop", title: "Amazon Kendra Workshop", description: "Build intelligent search with Amazon Kendra for enterprise document search and FAQ retrieval.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/kendra/", instructions: "Create Kendra index, configure data sources, tune relevance, implement search UI, add FAQ", resources: [res("kendra-kw-1","AWS::Kendra::Index",0.274)] },
  // ── Serverless Advanced ──
  { workshopId: "lambda-powertools", title: "AWS Lambda Powertools Workshop", description: "Build production-ready Lambda functions with AWS Lambda Powertools for structured logging, tracing, and metrics.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/lambda/", instructions: "Add structured logging, implement distributed tracing with X-Ray, emit custom metrics, use idempotency utility", resources: [res("lambda-lp-1","AWS::Lambda::Function",0,{freeTier:true}), res("dynamodb-lp-1","AWS::DynamoDB::Table",0,{freeTier:true})] },
  { workshopId: "sam-workshop", title: "AWS SAM Workshop", description: "Build and deploy serverless applications with AWS Serverless Application Model (SAM) CLI.", category: "Serverless", difficulty: "beginner", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/serverless/sam/", instructions: "Initialize SAM project, define resources in template, local testing, deploy with SAM CLI, configure CI/CD", resources: [res("lambda-sam-1","AWS::Lambda::Function",0,{freeTier:true}), res("apigw-sam-1","AWS::ApiGateway::RestApi",0,{freeTier:true})] },
  { workshopId: "lambda-container-workshop", title: "Lambda Container Images Workshop", description: "Package and deploy Lambda functions as container images up to 10GB for complex dependencies.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 90, costBadge: "free", sourceUrl: "https://aws.amazon.com/lambda/", instructions: "Build container image for Lambda, push to ECR, deploy function, test locally with RIE", resources: [res("lambda-lci-1","AWS::Lambda::Function",0,{freeTier:true}), res("ecr-lci-1","AWS::ECR::Repository",0)] },
  // ── Developer Tools ──
  { workshopId: "codecatalyst-workshop", title: "Amazon CodeCatalyst Workshop", description: "Accelerate software development with Amazon CodeCatalyst for unified dev environments, CI/CD, and project management.", category: "DevOps", difficulty: "beginner", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/codecatalyst/", instructions: "Create CodeCatalyst space, set up project, configure dev environments, build CI/CD workflows", resources: [res("codecatalyst-cc-1","AWS::CodeCatalyst::Project",0,{freeTier:true})] },
  { workshopId: "codewhisperer-workshop", title: "Amazon CodeWhisperer Workshop", description: "Boost developer productivity with AI-powered code suggestions from Amazon CodeWhisperer.", category: "DevOps", difficulty: "beginner", estimatedDuration: 60, costBadge: "free", sourceUrl: "https://aws.amazon.com/q/developer/", instructions: "Install CodeWhisperer plugin, generate code suggestions, review security scans, customize recommendations", resources: [] },
  { workshopId: "proton-workshop", title: "AWS Proton Workshop", description: "Automate infrastructure provisioning for container and serverless applications with AWS Proton.", category: "DevOps", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/proton/", instructions: "Create environment templates, define service templates, deploy environments, provision services", resources: [res("ecs-pr-1","AWS::ECS::Cluster",0), res("fargate-pr-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"})] },
  { workshopId: "fault-injection-workshop", title: "AWS Fault Injection Simulator Workshop", description: "Test application resilience with controlled chaos engineering experiments using AWS FIS.", category: "DevOps", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/fis/", instructions: "Create experiment templates, target EC2 and ECS resources, run CPU stress tests, simulate AZ failures", resources: [res("ec2-fis-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("ec2-fis-2","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  // ── Containers Advanced ──
  { workshopId: "eks-security-workshop", title: "Amazon EKS Security Workshop", description: "Secure Kubernetes workloads on EKS with pod security, IRSA, network policies, and secrets management.", category: "Containers", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Configure IRSA, implement pod security standards, set up network policies, manage secrets with Secrets Manager", resources: [res("eks-es-1","AWS::EKS::Cluster",0.10), res("ec2-es-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("ec2-es-2","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  { workshopId: "eks-observability", title: "EKS Observability Workshop", description: "Implement observability for EKS with CloudWatch Container Insights, Prometheus, Grafana, and OpenTelemetry.", category: "Containers", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Deploy Container Insights, set up Prometheus and Grafana, configure OpenTelemetry collector, create dashboards", resources: [res("eks-eo-1","AWS::EKS::Cluster",0.10), res("ec2-eo-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("grafana-eo-1","AWS::Grafana::Workspace",0.01)] },
  { workshopId: "copilot-workshop", title: "AWS Copilot Workshop", description: "Deploy containerized applications on ECS with AWS Copilot CLI for simplified container management.", category: "Containers", difficulty: "beginner", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/containers/copilot/", instructions: "Initialize Copilot application, deploy services, configure environments, set up CI/CD pipeline", resources: [res("ecs-cp-1","AWS::ECS::Cluster",0), res("fargate-cp-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"})] },
  // ── Database Advanced ──
  { workshopId: "neptune-workshop", title: "Amazon Neptune Workshop", description: "Build graph database applications with Amazon Neptune for social networks, knowledge graphs, and fraud detection.", category: "Database", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/neptune/", instructions: "Create Neptune cluster, load graph data, query with Gremlin and SPARQL, visualize graph relationships", resources: [res("neptune-nw-1","AWS::Neptune::DBCluster",0.096,{instanceType:"db.t3.medium"})] },
  { workshopId: "documentdb-workshop", title: "Amazon DocumentDB Workshop", description: "Build document database applications with Amazon DocumentDB (MongoDB compatible) for JSON workloads.", category: "Database", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/documentdb/", instructions: "Create DocumentDB cluster, connect with MongoDB drivers, perform CRUD operations, configure indexes", resources: [res("docdb-dw-1","AWS::DocDB::DBCluster",0.076,{instanceType:"db.t3.medium"})] },
  { workshopId: "keyspaces-workshop", title: "Amazon Keyspaces Workshop", description: "Build scalable applications with Amazon Keyspaces (Apache Cassandra compatible) for wide-column workloads.", category: "Database", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/keyspaces/", instructions: "Create keyspaces and tables, perform CQL operations, configure capacity modes, implement data modeling patterns", resources: [res("keyspaces-kw-1","AWS::Cassandra::Table",0.012)] },
  { workshopId: "timestream-workshop", title: "Amazon Timestream Workshop", description: "Store and analyze time-series data with Amazon Timestream for IoT and operational metrics.", category: "Database", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/timestream/", instructions: "Create Timestream database and tables, ingest time-series data, query with SQL, visualize with Grafana", resources: [res("timestream-tw-1","AWS::Timestream::Database",0), res("timestream-tw-2","AWS::Timestream::Table",0.01)] },
  { workshopId: "memorydb-workshop", title: "Amazon MemoryDB Workshop", description: "Build ultra-fast applications with Amazon MemoryDB for Redis-compatible in-memory database with durability.", category: "Database", difficulty: "intermediate", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/memorydb/", instructions: "Create MemoryDB cluster, connect with Redis clients, implement caching patterns, test durability", resources: [res("memorydb-mw-1","AWS::MemoryDB::Cluster",0.068,{instanceType:"db.t4g.small"})] },
];
