/**
 * Official AWS Workshop data definitions
 * All workshops are from official AWS sources (catalog.workshops.aws, eksworkshop.com, etc.)
 * Used by seed-workshops.ts
 */

// Helper to build a resource entry
function res(
  id: string, type: string, hourly: number,
  opts: { instanceType?: string; freeTier?: boolean; method?: string; storageSize?: number } = {}
) {
  return {
    resourceId: id, resourceType: type,
    configuration: { region: "us-east-1", instanceType: opts.instanceType, storageSize: opts.storageSize },
    pricing: { hourlyRate: hourly, dailyCost: +(hourly * 24).toFixed(4), monthlyCost: +(hourly * 730).toFixed(2), pricingModel: "On-Demand" },
    freeTierEligible: opts.freeTier ?? false, deploymentMethod: opts.method ?? "CloudFormation",
  };
}

export type WorkshopDef = {
  workshopId: string; title: string; description: string; category: string;
  difficulty: string; estimatedDuration: number; costBadge: string;
  sourceUrl: string; instructions: string; resources: ReturnType<typeof res>[];
};

export const workshops: WorkshopDef[] = [
  // ── Serverless ──
  { workshopId: "serverless-web-app", title: "Build a Serverless Web Application", description: "Build a serverless web application using AWS Lambda, Amazon API Gateway, AWS Amplify, Amazon DynamoDB, and Amazon Cognito.", category: "Serverless", difficulty: "beginner", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/getting-started/hands-on/build-serverless-web-app-lambda-apigateway-s3-dynamodb-cognito/", instructions: "Deploy Amplify frontend, create Cognito user pool, build Lambda backend, configure API Gateway, set up DynamoDB", resources: [res("lambda-swa-1","AWS::Lambda::Function",0,{freeTier:true}), res("apigw-swa-1","AWS::ApiGateway::RestApi",0,{freeTier:true}), res("dynamodb-swa-1","AWS::DynamoDB::Table",0,{freeTier:true}), res("cognito-swa-1","AWS::Cognito::UserPool",0,{freeTier:true})] },
  { workshopId: "event-driven-arch", title: "Event-Driven Architecture with Amazon EventBridge", description: "Design and implement event-driven microservices using Amazon EventBridge, Lambda, SQS, and SNS.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/eventbridge/", instructions: "Create EventBridge event bus, configure rules, build Lambda consumers, set up SQS/SNS targets", resources: [res("eventbridge-eda-1","AWS::Events::EventBus",0,{freeTier:true}), res("lambda-eda-1","AWS::Lambda::Function",0,{freeTier:true}), res("sqs-eda-1","AWS::SQS::Queue",0,{freeTier:true}), res("sns-eda-1","AWS::SNS::Topic",0,{freeTier:true})] },
  { workshopId: "serverless-image-processing", title: "Serverless Image Processing Workflow", description: "Build an image processing pipeline using AWS Step Functions, Lambda, S3, and Amazon Rekognition.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 150, costBadge: "low", sourceUrl: "https://aws.amazon.com/step-functions/", instructions: "Create S3 bucket for uploads, build Lambda functions for processing, configure Step Functions workflow, integrate Rekognition", resources: [res("s3-sip-1","AWS::S3::Bucket",0,{freeTier:true}), res("lambda-sip-1","AWS::Lambda::Function",0,{freeTier:true}), res("lambda-sip-2","AWS::Lambda::Function",0,{freeTier:true}), res("stepfn-sip-1","AWS::StepFunctions::StateMachine",0.025)] },
  { workshopId: "wild-rydes-serverless", title: "Wild Rydes Serverless Workshop", description: "Build a complete serverless ride-sharing web application with user management, real-time backend, and RESTful API.", category: "Serverless", difficulty: "beginner", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/getting-started/hands-on/build-web-app-s3-lambda-api-gateway-dynamodb/", instructions: "Host static website on S3, manage users with Cognito, build serverless backend with Lambda and DynamoDB, expose via API Gateway", resources: [res("s3-wr-1","AWS::S3::Bucket",0,{freeTier:true}), res("cognito-wr-1","AWS::Cognito::UserPool",0,{freeTier:true}), res("lambda-wr-1","AWS::Lambda::Function",0,{freeTier:true}), res("dynamodb-wr-1","AWS::DynamoDB::Table",0,{freeTier:true}), res("apigw-wr-1","AWS::ApiGateway::RestApi",0,{freeTier:true})] },
  { workshopId: "step-functions-workshop", title: "AWS Step Functions Workshop", description: "Learn to coordinate distributed applications and microservices using visual workflows with AWS Step Functions.", category: "Serverless", difficulty: "intermediate", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/step-functions/", instructions: "Create state machines, implement error handling, build parallel workflows, integrate with Lambda and DynamoDB", resources: [res("stepfn-sf-1","AWS::StepFunctions::StateMachine",0,{freeTier:true}), res("lambda-sf-1","AWS::Lambda::Function",0,{freeTier:true}), res("lambda-sf-2","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "serverless-security", title: "Serverless Security Workshop", description: "Learn techniques to secure serverless applications built with AWS Lambda, Amazon API Gateway, and RDS Aurora.", category: "Serverless", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/lambda/features/", instructions: "Implement IAM best practices, secure API Gateway endpoints, encrypt data at rest and in transit, configure VPC for Lambda", resources: [res("lambda-ss-1","AWS::Lambda::Function",0,{freeTier:true}), res("apigw-ss-1","AWS::ApiGateway::RestApi",0,{freeTier:true}), res("rds-ss-1","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true})] },
  { workshopId: "serverless-data-analytics", title: "Serverless Game Analytics Pipeline", description: "Build a serverless analytics pipeline for game telemetry using Kinesis, Lambda, S3, and Athena.", category: "Serverless", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/kinesis/data-firehose/", instructions: "Set up Kinesis Data Firehose, process events with Lambda, store in S3, query with Athena", resources: [res("kinesis-sga-1","AWS::KinesisFirehose::DeliveryStream",0.036), res("lambda-sga-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-sga-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Containers ──
  { workshopId: "eks-workshop", title: "Amazon EKS Workshop", description: "Deploy and manage containerized applications on Amazon Elastic Kubernetes Service with managed node groups, Fargate, and observability.", category: "Containers", difficulty: "intermediate", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Create EKS cluster, deploy microservices, configure Ingress, set up monitoring with CloudWatch Container Insights", resources: [res("eks-ew-1","AWS::EKS::Cluster",0.10), res("ec2-ew-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("ec2-ew-2","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("nat-ew-1","AWS::EC2::NatGateway",0.045)] },
  { workshopId: "ecs-fargate-workshop", title: "Amazon ECS on Fargate Workshop", description: "Deploy containerized microservices on AWS Fargate without managing servers using Amazon ECS.", category: "Containers", difficulty: "intermediate", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/ecs/", instructions: "Create ECS cluster, deploy frontend and backend Fargate services, configure service discovery and load balancing", resources: [res("ecs-fw-1","AWS::ECS::Cluster",0), res("fargate-fw-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("fargate-fw-2","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("alb-fw-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225)] },
  { workshopId: "app-runner-workshop", title: "AWS App Runner Workshop", description: "Deploy web applications and APIs at scale with AWS App Runner from source code or container images.", category: "Containers", difficulty: "beginner", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/apprunner/", instructions: "Create App Runner service from source code, configure auto scaling, set up custom domains, deploy from ECR", resources: [res("apprunner-ar-1","AWS::AppRunner::Service",0.007), res("ecr-ar-1","AWS::ECR::Repository",0)] },
  { workshopId: "app-mesh-workshop", title: "AWS App Mesh Workshop", description: "Learn service mesh networking with AWS App Mesh for microservices running on ECS and EKS.", category: "Containers", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/app-mesh/", instructions: "Deploy ECS services, configure App Mesh virtual nodes, routers, and services, implement traffic management", resources: [res("ecs-am-1","AWS::ECS::Cluster",0), res("fargate-am-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("fargate-am-2","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("alb-am-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225)] },
  { workshopId: "containers-immersion-day", title: "Containers Immersion Day", description: "Comprehensive hands-on workshop covering Docker fundamentals, ECS, Fargate, and container orchestration on AWS.", category: "Containers", difficulty: "intermediate", estimatedDuration: 480, costBadge: "medium", sourceUrl: "https://aws.amazon.com/containers/", instructions: "Build Docker images, push to ECR, deploy on ECS with Fargate, configure ALB, implement CI/CD", resources: [res("ecs-cid-1","AWS::ECS::Cluster",0), res("fargate-cid-1","AWS::ECS::Service",0.04048,{instanceType:"0.5 vCPU / 1GB"}), res("ecr-cid-1","AWS::ECR::Repository",0), res("alb-cid-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225), res("nat-cid-1","AWS::EC2::NatGateway",0.045)] },
  { workshopId: "blue-green-eks", title: "Blue/Green Deployment with Amazon EKS", description: "Implement blue/green deployment strategies on Amazon EKS for zero-downtime application updates.", category: "Containers", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/eks/", instructions: "Create EKS cluster, configure blue/green deployment, implement traffic shifting with ALB", resources: [res("eks-bg-1","AWS::EKS::Cluster",0.10), res("ec2-bg-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("ec2-bg-2","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("alb-bg-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225), res("nat-bg-1","AWS::EC2::NatGateway",0.045)] },
  // ── Machine Learning ──
  { workshopId: "sagemaker-ml", title: "Amazon SageMaker Immersion Day", description: "Build, train, and deploy machine learning models using Amazon SageMaker notebooks, training jobs, and endpoints.", category: "Machine Learning", difficulty: "advanced", estimatedDuration: 480, costBadge: "high", sourceUrl: "https://aws.amazon.com/sagemaker/", instructions: "Set up SageMaker Studio, prepare data, train models with built-in algorithms, deploy endpoints, monitor with Model Monitor", resources: [res("sagemaker-sm-1","AWS::SageMaker::NotebookInstance",0.0464,{instanceType:"ml.t3.medium"}), res("s3-sm-1","AWS::S3::Bucket",0.001), res("sagemaker-ep-1","AWS::SageMaker::Endpoint",0.0464,{instanceType:"ml.t3.medium"})] },
  { workshopId: "sagemaker-autopilot", title: "Amazon SageMaker Autopilot Workshop", description: "Use SageMaker Autopilot to automatically build, train, and tune the best ML models based on your data.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/sagemaker/autopilot/", instructions: "Upload dataset to S3, create Autopilot experiment, review generated notebooks, deploy best model", resources: [res("sagemaker-ap-1","AWS::SageMaker::NotebookInstance",0.0464,{instanceType:"ml.t3.medium"}), res("s3-ap-1","AWS::S3::Bucket",0.001)] },
  { workshopId: "bedrock-workshop", title: "Amazon Bedrock Workshop", description: "Build generative AI applications using Amazon Bedrock foundation models including text generation, summarization, and image generation.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/bedrock/", instructions: "Access Bedrock console, invoke foundation models via API, build RAG applications, implement guardrails", resources: [res("bedrock-bw-1","AWS::Bedrock::Agent",0.01), res("lambda-bw-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-bw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "rekognition-immersion", title: "Amazon Rekognition Immersion Day", description: "Build computer vision applications using Amazon Rekognition for image and video analysis, face detection, and content moderation.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/rekognition/", instructions: "Detect objects and faces in images, analyze video streams, implement content moderation, build custom labels", resources: [res("lambda-rek-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-rek-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "textract-workshop", title: "Amazon Textract Workshop", description: "Extract text, forms, and tables from documents using Amazon Textract with intelligent document processing.", category: "Machine Learning", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/textract/", instructions: "Analyze documents with Textract API, extract forms and tables, process invoices, build document pipelines", resources: [res("lambda-tx-1","AWS::Lambda::Function",0,{freeTier:true}), res("s3-tx-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Security ──
  { workshopId: "iam-security", title: "AWS IAM Security Best Practices", description: "Learn IAM best practices including least privilege, MFA, roles, policies, and AWS Organizations SCPs.", category: "Security", difficulty: "intermediate", estimatedDuration: 90, costBadge: "free", sourceUrl: "https://aws.amazon.com/iam/", instructions: "Create IAM policies, configure roles, implement MFA, set up Organizations SCPs, audit with Access Analyzer", resources: [res("iam-sec-1","AWS::IAM::Role",0,{freeTier:true}), res("iam-sec-2","AWS::IAM::Policy",0,{freeTier:true})] },
  { workshopId: "security-hub-workshop", title: "AWS Security Hub Workshop", description: "Centralize security findings with AWS Security Hub, GuardDuty, Inspector, and Macie.", category: "Security", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/security-hub/", instructions: "Enable Security Hub, configure GuardDuty, run Inspector assessments, set up Macie for data discovery", resources: [res("sechub-sh-1","AWS::SecurityHub::Hub",0.0001), res("guardduty-sh-1","AWS::GuardDuty::Detector",0.004), res("inspector-sh-1","AWS::Inspector::AssessmentTemplate",0)] },
  { workshopId: "guardduty-workshop", title: "Amazon GuardDuty Workshop", description: "Detect threats and malicious activity in your AWS environment using Amazon GuardDuty intelligent threat detection.", category: "Security", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/guardduty/", instructions: "Enable GuardDuty, generate sample findings, configure notifications, remediate threats with Lambda", resources: [res("guardduty-gd-1","AWS::GuardDuty::Detector",0.004), res("lambda-gd-1","AWS::Lambda::Function",0,{freeTier:true}), res("sns-gd-1","AWS::SNS::Topic",0,{freeTier:true})] },
  { workshopId: "waf-workshop", title: "AWS WAF Workshop", description: "Protect web applications from common exploits using AWS WAF with managed rules and custom rules.", category: "Security", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/waf/", instructions: "Create WAF WebACL, configure managed rule groups, build custom rules, test with simulated attacks", resources: [res("waf-wf-1","AWS::WAFv2::WebACL",0.005), res("alb-wf-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225)] },
  { workshopId: "security-odyssey", title: "AWS Security Odyssey", description: "Comprehensive security workshop covering identity, detection, infrastructure protection, data protection, and incident response.", category: "Security", difficulty: "advanced", estimatedDuration: 480, costBadge: "low", sourceUrl: "https://aws.amazon.com/security/", instructions: "Implement defense in depth, configure detective controls, protect data at rest and in transit, build incident response playbooks", resources: [res("ec2-so-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("guardduty-so-1","AWS::GuardDuty::Detector",0.004), res("config-so-1","AWS::Config::ConfigurationRecorder",0.003)] },
  { workshopId: "control-tower-workshop", title: "AWS Control Tower Workshop", description: "Set up and govern a secure multi-account AWS environment using AWS Control Tower with guardrails and landing zones.", category: "Security", difficulty: "advanced", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/controltower/", instructions: "Set up landing zone, configure guardrails, create organizational units, provision accounts with Account Factory", resources: [res("org-ct-1","AWS::Organizations::Organization",0,{freeTier:true}), res("config-ct-1","AWS::Config::ConfigurationRecorder",0.003), res("cloudtrail-ct-1","AWS::CloudTrail::Trail",0)] },
  // ── Networking ──
  { workshopId: "vpc-networking", title: "Advanced VPC Networking", description: "Design and implement complex VPC architectures with Transit Gateway, PrivateLink, and VPC peering.", category: "Networking", difficulty: "advanced", estimatedDuration: 150, costBadge: "medium", sourceUrl: "https://aws.amazon.com/vpc/", instructions: "Create multi-VPC architecture, configure Transit Gateway, set up PrivateLink endpoints, implement VPC peering", resources: [res("tgw-vn-1","AWS::EC2::TransitGateway",0.05), res("nat-vn-1","AWS::EC2::NatGateway",0.045), res("ec2-vn-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "cloudfront-cdn", title: "Amazon CloudFront CDN Workshop", description: "Accelerate content delivery with CloudFront distributions, Lambda@Edge, and CloudFront Functions.", category: "Networking", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/cloudfront/", instructions: "Create CloudFront distribution, configure origins, implement Lambda@Edge functions, set up CloudFront Functions", resources: [res("cf-cdn-1","AWS::CloudFront::Distribution",0,{freeTier:true}), res("s3-cdn-1","AWS::S3::Bucket",0,{freeTier:true}), res("lambda-cdn-1","AWS::Lambda::Function",0,{freeTier:true})] },
  { workshopId: "network-firewall", title: "AWS Network Firewall Workshop", description: "Deploy and configure AWS Network Firewall for stateful inspection, intrusion prevention, and web filtering.", category: "Networking", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/network-firewall/", instructions: "Deploy Network Firewall, create stateful and stateless rule groups, configure logging, test traffic filtering", resources: [res("nfw-nf-1","AWS::NetworkFirewall::Firewall",0.395), res("nat-nf-1","AWS::EC2::NatGateway",0.045), res("ec2-nf-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "vpc-endpoint-workshop", title: "VPC Endpoint Workshop", description: "Securely access AWS services from your VPC without traversing the internet using VPC endpoints.", category: "Networking", difficulty: "intermediate", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/privatelink/", instructions: "Create Gateway and Interface VPC endpoints, configure endpoint policies, test private connectivity to S3 and DynamoDB", resources: [res("vpce-ve-1","AWS::EC2::VPCEndpoint",0.01), res("ec2-ve-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "ipv6-networking", title: "IPv6 Networking Workshop", description: "Implement IPv6 networking on AWS with dual-stack VPCs, Transit Gateway, and traffic mirroring.", category: "Networking", difficulty: "advanced", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/vpc/ipv6/", instructions: "Configure dual-stack VPC, enable IPv6 on subnets, set up Transit Gateway with IPv6, implement traffic mirroring", resources: [res("tgw-ipv6-1","AWS::EC2::TransitGateway",0.05), res("ec2-ipv6-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  // ── Database ──
  { workshopId: "dynamodb-deep-dive", title: "Amazon DynamoDB Labs", description: "Master DynamoDB data modeling, performance optimization, global tables, streams, and advanced query patterns.", category: "Database", difficulty: "intermediate", estimatedDuration: 240, costBadge: "free", sourceUrl: "https://aws.amazon.com/dynamodb/", instructions: "Design single-table data models, implement GSI/LSI, configure DynamoDB Streams, set up global tables", resources: [res("dynamodb-dd-1","AWS::DynamoDB::Table",0,{freeTier:true}), res("dynamodb-dd-2","AWS::DynamoDB::Table",0,{freeTier:true})] },
  { workshopId: "aurora-serverless", title: "Amazon Aurora Serverless v2 Workshop", description: "Deploy and manage Aurora Serverless v2 for MySQL and PostgreSQL with automatic scaling.", category: "Database", difficulty: "intermediate", estimatedDuration: 150, costBadge: "medium", sourceUrl: "https://aws.amazon.com/rds/aurora/serverless/", instructions: "Create Aurora Serverless v2 cluster, configure ACU scaling, test auto-scaling behavior, implement read replicas", resources: [res("aurora-as-1","AWS::RDS::DBCluster",0.12,{instanceType:"db.r5.large"})] },
  { workshopId: "elasticache-redis", title: "Amazon ElastiCache for Redis Workshop", description: "Build high-performance caching layers with ElastiCache for Redis including cluster mode and Global Datastore.", category: "Database", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/elasticache/redis/", instructions: "Create Redis cluster, implement caching patterns, configure cluster mode, set up Global Datastore for cross-region replication", resources: [res("redis-ec-1","AWS::ElastiCache::CacheCluster",0.017,{instanceType:"cache.t3.micro"})] },
  { workshopId: "rds-purpose-built", title: "Amazon RDS Purpose-Built Databases", description: "Explore purpose-built databases on AWS including RDS, Aurora, DynamoDB, Neptune, and DocumentDB.", category: "Database", difficulty: "intermediate", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/rds/", instructions: "Deploy RDS instances, migrate data between engines, compare performance characteristics, implement multi-AZ", resources: [res("rds-pb-1","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true}), res("rds-pb-2","AWS::RDS::DBInstance",0.034,{instanceType:"db.t3.small"})] },
  { workshopId: "redshift-immersion", title: "Amazon Redshift Immersion Day", description: "Deep dive into Amazon Redshift for data warehousing with loading, querying, and performance tuning.", category: "Database", difficulty: "advanced", estimatedDuration: 480, costBadge: "medium", sourceUrl: "https://aws.amazon.com/redshift/", instructions: "Create Redshift cluster, load data from S3, optimize queries, configure workload management, implement Redshift Spectrum", resources: [res("redshift-ri-1","AWS::Redshift::Cluster",0.25,{instanceType:"dc2.large"}), res("s3-ri-1","AWS::S3::Bucket",0.001)] },
  { workshopId: "qldb-immersion", title: "Amazon QLDB Immersion Day", description: "Build applications with Amazon Quantum Ledger Database for immutable, cryptographically verifiable transaction logs.", category: "Database", difficulty: "intermediate", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/qldb/", instructions: "Create QLDB ledger, write PartiQL queries, verify document history, stream changes to Kinesis", resources: [res("qldb-qi-1","AWS::QLDB::Ledger",0.025)] },
  // ── DevOps ──
  { workshopId: "cdk-workshop", title: "AWS CDK Workshop", description: "Learn Infrastructure as Code with AWS CDK using TypeScript to define cloud resources programmatically.", category: "DevOps", difficulty: "beginner", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/cdk/", instructions: "Install CDK CLI, create new project, define constructs, deploy stacks, write tests for infrastructure", resources: [res("lambda-cdk-1","AWS::Lambda::Function",0,{freeTier:true}), res("apigw-cdk-1","AWS::ApiGateway::RestApi",0,{freeTier:true})] },
  { workshopId: "cicd-pipeline", title: "CI/CD Pipeline with AWS CodePipeline", description: "Build end-to-end CI/CD pipelines using CodeCommit, CodeBuild, CodeDeploy, and CodePipeline.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 150, costBadge: "free", sourceUrl: "https://aws.amazon.com/codepipeline/", instructions: "Create CodeCommit repo, configure CodeBuild project, set up CodeDeploy application, orchestrate with CodePipeline", resources: [res("codecommit-ci-1","AWS::CodeCommit::Repository",0,{freeTier:true}), res("codebuild-ci-1","AWS::CodeBuild::Project",0.005), res("codepipeline-ci-1","AWS::CodePipeline::Pipeline",0,{freeTier:true})] },
  { workshopId: "observability-workshop", title: "AWS One Observability Workshop", description: "Implement full-stack observability with CloudWatch, X-Ray, OpenTelemetry, and Managed Grafana.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/cloudwatch/", instructions: "Set up CloudWatch dashboards, configure X-Ray tracing, deploy OpenTelemetry collector, create Grafana dashboards", resources: [res("cw-obs-1","AWS::CloudWatch::Dashboard",0.004), res("ec2-obs-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("grafana-obs-1","AWS::Grafana::Workspace",0.01)] },
  { workshopId: "cloudformation-workshop", title: "AWS CloudFormation Workshop", description: "Master Infrastructure as Code with AWS CloudFormation templates, stacks, nested stacks, and drift detection.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 180, costBadge: "free", sourceUrl: "https://aws.amazon.com/cloudformation/", instructions: "Write CloudFormation templates, create and update stacks, use nested stacks, implement drift detection", resources: [res("s3-cfn-1","AWS::S3::Bucket",0,{freeTier:true}), res("ec2-cfn-1","AWS::EC2::Instance",0,{freeTier:true})] },
  { workshopId: "devsecops-workshop", title: "DevSecOps Workshop", description: "Integrate security into your CI/CD pipeline with automated security testing, code analysis, and compliance checks.", category: "DevOps", difficulty: "advanced", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/devops/", instructions: "Set up CodePipeline with security stages, integrate SAST/DAST tools, automate compliance checks, implement security gates", resources: [res("codepipeline-ds-1","AWS::CodePipeline::Pipeline",0,{freeTier:true}), res("codebuild-ds-1","AWS::CodeBuild::Project",0.005), res("ecr-ds-1","AWS::ECR::Repository",0)] },
  { workshopId: "systems-manager-workshop", title: "AWS Systems Manager Workshop", description: "Manage and configure EC2 instances at scale using AWS Systems Manager with Session Manager, Patch Manager, and Run Command.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/systems-manager/", instructions: "Configure SSM Agent, use Session Manager for secure access, set up Patch Manager baselines, run commands at scale", resources: [res("ec2-ssm-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("ec2-ssm-2","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "well-architected-labs", title: "AWS Well-Architected Labs", description: "Hands-on labs for the six pillars of the Well-Architected Framework: operational excellence, security, reliability, performance, cost optimization, and sustainability.", category: "DevOps", difficulty: "intermediate", estimatedDuration: 480, costBadge: "low", sourceUrl: "https://aws.amazon.com/architecture/well-architected/", instructions: "Review workloads against Well-Architected pillars, implement best practices, use the Well-Architected Tool", resources: [res("ec2-wa-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("s3-wa-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Analytics ──
  { workshopId: "athena-analytics", title: "Serverless Analytics with Amazon Athena", description: "Query data in S3 using Amazon Athena, AWS Glue crawlers, and build dashboards with QuickSight.", category: "Analytics", difficulty: "beginner", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/athena/", instructions: "Create Glue crawlers, define Athena tables, run SQL queries on S3 data, visualize with QuickSight", resources: [res("s3-ath-1","AWS::S3::Bucket",0,{freeTier:true}), res("glue-ath-1","AWS::Glue::Crawler",0.0044)] },
  { workshopId: "kinesis-streaming", title: "Real-Time Streaming with Amazon Kinesis", description: "Build real-time data streaming pipelines with Kinesis Data Streams, Firehose, and Analytics.", category: "Analytics", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/kinesis/", instructions: "Create Kinesis Data Stream, configure Firehose delivery, build real-time analytics with Kinesis Analytics", resources: [res("kinesis-ks-1","AWS::Kinesis::Stream",0.015), res("firehose-ks-1","AWS::KinesisFirehose::DeliveryStream",0.036), res("s3-ks-1","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "quicksight-workshop", title: "Amazon QuickSight Workshop", description: "Build interactive dashboards and visualizations with Amazon QuickSight for business intelligence.", category: "Analytics", difficulty: "beginner", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/quicksight/", instructions: "Connect data sources, create analyses, build dashboards, share with users, configure row-level security", resources: [res("quicksight-qs-1","AWS::QuickSight::Dashboard",0.03)] },
  { workshopId: "emr-workshop", title: "Amazon EMR Workshop", description: "Process big data with Amazon EMR using Apache Spark, Hive, and Presto on managed Hadoop clusters.", category: "Analytics", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/emr/", instructions: "Create EMR cluster, run Spark jobs, query with Hive and Presto, configure auto-scaling, use EMR on EKS", resources: [res("emr-em-1","AWS::EMR::Cluster",0.096,{instanceType:"m5.large"}), res("s3-em-1","AWS::S3::Bucket",0.001)] },
  { workshopId: "data-lake-immersion", title: "Serverless Data Lake Immersion Day", description: "Build a serverless data lake on AWS using S3, Glue, Athena, and Lake Formation.", category: "Analytics", difficulty: "intermediate", estimatedDuration: 480, costBadge: "low", sourceUrl: "https://aws.amazon.com/big-data/datalakes-and-analytics/", instructions: "Set up S3 data lake, configure Glue ETL jobs, query with Athena, manage access with Lake Formation", resources: [res("s3-dl-1","AWS::S3::Bucket",0,{freeTier:true}), res("glue-dl-1","AWS::Glue::Job",0.0044), res("lakeformation-dl-1","AWS::LakeFormation::DataLakeSettings",0)] },
  { workshopId: "glue-workshop", title: "AWS Glue Workshop", description: "Build serverless ETL pipelines with AWS Glue for data integration, transformation, and cataloging.", category: "Analytics", difficulty: "intermediate", estimatedDuration: 180, costBadge: "low", sourceUrl: "https://aws.amazon.com/glue/", instructions: "Create Glue crawlers, build ETL jobs with PySpark, configure data catalog, implement data quality checks", resources: [res("glue-gw-1","AWS::Glue::Job",0.0044), res("glue-gw-2","AWS::Glue::Crawler",0.0044), res("s3-gw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── Storage ──
  { workshopId: "s3-masterclass", title: "Amazon S3 Masterclass", description: "Deep dive into S3 features: versioning, lifecycle policies, replication, access points, and S3 Object Lambda.", category: "Storage", difficulty: "intermediate", estimatedDuration: 120, costBadge: "free", sourceUrl: "https://aws.amazon.com/s3/", instructions: "Configure versioning, set up lifecycle rules, implement cross-region replication, create access points, use S3 Object Lambda", resources: [res("s3-mc-1","AWS::S3::Bucket",0,{freeTier:true}), res("s3-mc-2","AWS::S3::Bucket",0,{freeTier:true})] },
  { workshopId: "efs-workshop", title: "Amazon EFS Workshop", description: "Set up shared file storage with Amazon EFS for EC2 instances and Lambda functions with performance modes.", category: "Storage", difficulty: "intermediate", estimatedDuration: 90, costBadge: "low", sourceUrl: "https://aws.amazon.com/efs/", instructions: "Create EFS file system, mount on EC2 instances, configure performance modes, integrate with Lambda", resources: [res("efs-ef-1","AWS::EFS::FileSystem",0.008), res("ec2-ef-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  { workshopId: "fsx-lustre-workshop", title: "Amazon FSx for Lustre Workshop", description: "Deploy high-performance file systems with Amazon FSx for Lustre for compute-intensive workloads.", category: "Storage", difficulty: "advanced", estimatedDuration: 120, costBadge: "medium", sourceUrl: "https://aws.amazon.com/fsx/lustre/", instructions: "Create FSx for Lustre file system, link to S3, run HPC workloads, monitor performance", resources: [res("fsx-fl-1","AWS::FSx::FileSystem",0.14,{storageSize:1200}), res("ec2-fl-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"})] },
  { workshopId: "backup-workshop", title: "AWS Backup Workshop", description: "Implement centralized backup management with AWS Backup for EC2, RDS, EFS, DynamoDB, and S3.", category: "Storage", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/backup/", instructions: "Create backup plans, configure backup vaults, set up cross-region backup, implement backup policies with Organizations", resources: [res("ec2-bk-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("rds-bk-1","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true})] },
  { workshopId: "datasync-workshop", title: "AWS DataSync Workshop", description: "Transfer data between on-premises storage and AWS using AWS DataSync with automated scheduling.", category: "Storage", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/datasync/", instructions: "Deploy DataSync agent, create transfer tasks, configure scheduling, monitor transfer progress", resources: [res("s3-ds-1","AWS::S3::Bucket",0,{freeTier:true}), res("ec2-ds-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
  // ── Compute ──
  { workshopId: "ec2-spot-workshop", title: "Amazon EC2 Spot Instances Workshop", description: "Optimize costs by running fault-tolerant workloads on EC2 Spot Instances with up to 90% savings.", category: "Compute", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/ec2/spot/", instructions: "Launch Spot Instances, configure Spot Fleet, implement interruption handling, use Spot with Auto Scaling", resources: [res("ec2-spot-1","AWS::EC2::SpotFleet",0.03,{instanceType:"m5.large"})] },
  { workshopId: "graviton-workshop", title: "AWS Graviton Workshop", description: "Migrate workloads to AWS Graviton (ARM) processors for better price-performance across EC2, ECS, and Lambda.", category: "Compute", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/ec2/graviton/", instructions: "Build ARM-compatible images, deploy on Graviton instances, benchmark performance, migrate containers to ARM", resources: [res("ec2-grav-1","AWS::EC2::Instance",0.0408,{instanceType:"t4g.medium"}), res("ec2-grav-2","AWS::EC2::Instance",0.0408,{instanceType:"t4g.medium"})] },
  { workshopId: "auto-scaling-workshop", title: "EC2 Auto Scaling Workshop", description: "Implement dynamic scaling with EC2 Auto Scaling groups, target tracking, step scaling, and predictive scaling.", category: "Compute", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/ec2/autoscaling/", instructions: "Create launch templates, configure Auto Scaling groups, set up scaling policies, test with load generation", resources: [res("ec2-as-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("alb-as-1","AWS::ElasticLoadBalancingV2::LoadBalancer",0.0225)] },
  { workshopId: "lightsail-workshop", title: "Amazon Lightsail Workshop", description: "Deploy and manage simple web applications and websites with Amazon Lightsail virtual private servers.", category: "Compute", difficulty: "beginner", estimatedDuration: 60, costBadge: "low", sourceUrl: "https://aws.amazon.com/lightsail/", instructions: "Create Lightsail instance, deploy WordPress, configure networking, set up load balancer", resources: [res("lightsail-ls-1","AWS::Lightsail::Instance",0.005)] },
  { workshopId: "batch-workshop", title: "AWS Batch Workshop", description: "Run batch computing workloads at scale with AWS Batch for job scheduling and compute resource management.", category: "Compute", difficulty: "advanced", estimatedDuration: 180, costBadge: "medium", sourceUrl: "https://aws.amazon.com/batch/", instructions: "Create compute environments, define job definitions, submit jobs, configure job queues and scheduling", resources: [res("batch-bw-1","AWS::Batch::ComputeEnvironment",0.096,{instanceType:"m5.large"}), res("s3-bw-1","AWS::S3::Bucket",0,{freeTier:true})] },
  // ── IoT ──
  { workshopId: "iot-core-workshop", title: "AWS IoT Core Workshop", description: "Connect devices to the cloud with AWS IoT Core, rules engine, device shadows, and MQTT messaging.", category: "IoT", difficulty: "intermediate", estimatedDuration: 150, costBadge: "free", sourceUrl: "https://aws.amazon.com/iot-core/", instructions: "Register IoT things, configure MQTT topics, set up rules engine actions, implement device shadows", resources: [res("iot-ic-1","AWS::IoT::Thing",0,{freeTier:true}), res("lambda-ic-1","AWS::Lambda::Function",0,{freeTier:true}), res("dynamodb-ic-1","AWS::DynamoDB::Table",0,{freeTier:true})] },
  { workshopId: "iot-greengrass-workshop", title: "AWS IoT Greengrass Workshop", description: "Deploy and manage edge computing with AWS IoT Greengrass for local processing, messaging, and ML inference.", category: "IoT", difficulty: "advanced", estimatedDuration: 240, costBadge: "low", sourceUrl: "https://aws.amazon.com/greengrass/", instructions: "Set up Greengrass core device, deploy components, run local Lambda functions, implement ML inference at edge", resources: [res("ec2-gg-1","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true}), res("iot-gg-1","AWS::IoT::Thing",0,{freeTier:true})] },
  { workshopId: "iot-analytics-workshop", title: "AWS IoT Analytics Workshop", description: "Process and analyze IoT data at scale with AWS IoT Analytics pipelines, data stores, and Jupyter notebooks.", category: "IoT", difficulty: "intermediate", estimatedDuration: 120, costBadge: "low", sourceUrl: "https://aws.amazon.com/iot-analytics/", instructions: "Create IoT Analytics channels, build data pipelines, configure data stores, analyze with Jupyter notebooks", resources: [res("iot-ia-1","AWS::IoTAnalytics::Channel",0.008), res("iot-ia-2","AWS::IoTAnalytics::Pipeline",0), res("iot-ia-3","AWS::IoTAnalytics::Datastore",0.008)] },
  // ── Migration ──
  { workshopId: "migration-hub", title: "AWS Migration Hub Workshop", description: "Plan and track application migrations using AWS Migration Hub, DMS, and Application Migration Service.", category: "Migration", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/migration-hub/", instructions: "Set up Migration Hub, discover applications, plan migration waves, execute with DMS and MGN", resources: [res("ec2-mh-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("dms-mh-1","AWS::DMS::ReplicationInstance",0.018,{instanceType:"dms.t3.micro"})] },
  { workshopId: "dms-immersion", title: "AWS DMS Immersion Day", description: "Migrate databases to AWS using Database Migration Service with schema conversion and continuous replication.", category: "Migration", difficulty: "intermediate", estimatedDuration: 480, costBadge: "medium", sourceUrl: "https://aws.amazon.com/dms/", instructions: "Set up source and target databases, create DMS replication instance, configure migration tasks, validate data", resources: [res("dms-di-1","AWS::DMS::ReplicationInstance",0.018,{instanceType:"dms.t3.micro"}), res("rds-di-1","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true}), res("rds-di-2","AWS::RDS::DBInstance",0.017,{instanceType:"db.t3.micro",freeTier:true})] },
  { workshopId: "app-migration-workshop", title: "Application Migration with AWS", description: "Migrate applications to AWS using CloudEndure Migration and AWS Application Migration Service (MGN).", category: "Migration", difficulty: "advanced", estimatedDuration: 240, costBadge: "medium", sourceUrl: "https://aws.amazon.com/application-migration-service/", instructions: "Install replication agent, configure launch settings, perform test migration, execute cutover", resources: [res("ec2-amw-1","AWS::EC2::Instance",0.096,{instanceType:"m5.large"}), res("ec2-amw-2","AWS::EC2::Instance",0.0116,{instanceType:"t3.micro",freeTier:true})] },
];

// Re-export the res helper for use in other data files
export { res };
